/**
 * Date
 */
let d = new Date()
console.log(d, 'date')
console.log(d.toDateString(), '1')
console.log(d.toISOString(), '2')
console.log(d.toJSON(), '3')
console.log(d.toLocaleDateString(), '4')
console.log(d.toLocaleString(), '5')
console.log(d.toLocaleTimeString(), '6')
console.log(d.toString(), '7')
console.log(d.toTimeString(), '8')
console.log(d.toUTCString(), '9')
console.log('-----------------------------------------------------------')
let a = new Date('2022-02-05T23:59:59').toISOString()
console.log(a, 'a')
let b = new Date('2022-02-05T23:59:59Z').toLocaleString()
console.log(b, 'b')
console.log(Date().toLocaleString())